# Generated by Django 5.1 on 2024-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
